CREATE TABLE FENOTIP(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (50)
);

CREATE TABLE GEN_TYPES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RECESSIVA_DOMINA VARCHAR (50)
);

CREATE TABLE GEN
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STRENGTH INT,
    FOREIGN KEY (TYPE_ID) REFERENCES GEN_TYPES(ID)
);

CREATE TABLE GENS_LIZARD_LIST(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (NAME_ID) REFERENCES GEN(ID)
);

CREATE TABLE LIZARD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (50),
    FOREIGN KEY (FATHER_ID) REFERENCES LIZARD(ID),
    FOREIGN KEY (MOTHER_ID) REFERENCES LIZARD(ID),
    FOREIGN KEY (MORPH_ID) REFERENCES FENOTIP(ID),
    FOREIGN KEY (GENS_LIST_ID) REFERENCES GENS_LIZARD_LIST(ID),
    MALE BOOLEAN,
    BREEDING_STATE BOOLEAN
);

INSERT INTO FENOTIP (NAME) VALUES ('ORANGE');
INSERT INTO GEN_TYPES (RECESSIVA_DOMINA) VALUES ('RECESSIVA');
INSERT INTO GEN_TYPES (RECESSIVA_DOMINA) VALUES ('DOMINA');
INSERT INTO GEN_TYPES (RECESSIVA_DOMINA) VALUES ('CO');
INSERT INTO GEN (STRENGTH, TYPE_ID) VALUES (3, 0);
INSERT INTO GENS_LIZARD_LIST (NAME_ID) VALUES (0);