services:
    php:
        build:
            context: '.'
            dockerfile: Dockerfile
        image: 'lizzard-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - 80:80
        volumes:
            - '../src:/var/www/html'